{{- if and .Values.metrics.enabled .Values.timesketch.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-timesketch-metrics
  labels:
    {{- include "timesketch.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.metrics.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: frontend
    {{- include "timesketch.selectorLabels" . | nindent 4 }}
{{- end }}