{{- if and (.Values.timesketch.ingress.enabled) (eq .Values.timesketch.ingress.className "gce") }}
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: {{ .Release.Name }}-timesketch-backendconfig
  namespace: {{ .Release.Namespace | quote }}
spec:
  timeoutSec: 300
  healthCheck:
    checkIntervalSec: 5
    timeoutSec: 5
    healthyThreshold: 2
    unhealthyThreshold: 2
    type: HTTP
    requestPath: /login/
    port: {{ .Values.timesketch.service.port }}
{{- end }}