{{- if and (.Values.timesketch.ingress.enabled) (eq .Values.timesketch.ingress.className "gce") }}
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: {{ .Release.Name }}-timesketch-frontendconfig
  namespace: {{ .Release.Namespace | quote }}
spec:
  redirectToHttps:
    enabled: true
{{- end }}