{{- $userconfigs := .Files.Glob .Values.timesketch.config.override }}
{{- if and $userconfigs .Values.timesketch.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-timesketch-config
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "timesketch.labels" . | nindent 4 }}
data:
{{ ($userconfigs).AsConfig | indent 2 }}
{{- end }}