{{- if and .Values.metrics.enabled .Values.turbinia.controller.enabled .Values.turbinia.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-turbinia-controller-metrics
  labels:
    {{- include "turbinia.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.metrics.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: controller
    {{- include "turbinia.selectorLabels" . | nindent 4 }}
{{- end }}