apiVersion: v2
name: osdfir-infrastructure
version: 0.3.2
description: A Helm chart for Open Source Digital Forensics Kubernetes deployments.
keywords:
- timesketch
- turbinia
- dfir
- analysis
- processing
- cloud
home: "https://github.com/google/osdfir-infrastructure"
dependencies:
  - condition: postgresql.enabled and timesketch.enabled
    name: postgresql
    version: 12.11.1
    repository: https://charts.bitnami.com/bitnami
  - condition: redis.enabled
    name: redis
    version: 18.0.4
    repository: https://charts.bitnami.com/bitnami
  - condition: opensearch.enabled and timesketch.enabled
    name: opensearch
    version: 2.14.1
    repository: https://opensearch-project.github.io/helm-charts/
  - condition: oauth2proxy.enabled
    name: oauth2-proxy
    alias: oauth2proxy
    version: 4.1.3
    repository: https://charts.bitnami.com/bitnami
maintainers:
  - name: Wajih Yassine
    url: https://github.com/wajihyassine
  - name: Johan Berggren
    url: https://github.com/berggren
  - name: Aaron Peterson
    url: https://github.com/aarontp
  - name: hacktobeer
    url: https://github.com/hacktobeer
sources:
- https://github.com/google/osdfir-infrastructure
- https://github.com/google/turbinia
- https://github.com/google/timesketch
annotations:
  category: Security
  licenses: Apache-2.0
