{{- $userconfigs := .Files.Get .Values.turbinia.config.override }}
{{- if .Values.turbinia.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-turbinia-server
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/component: server
    {{- include "turbinia.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: server
      {{- include "turbinia.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        # Have Deployment restart after each upgrade
        roll: {{ randAlphaNum 5 | quote }}
        {{- if .Values.metrics.enabled }}
        prometheus.io/port: {{ .Values.metrics.port | quote }}
        prometheus.io/scrape: "true"
        {{- end }}
      labels:
        app.kubernetes.io/component: server
        {{- include "turbinia.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.turbinia.gcp.enabled }} 
      serviceAccountName: {{ .Values.turbinia.gcp.serviceAccountName }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.turbinia.server.podSecurityContext | nindent 8 }}
      initContainers:
      {{- include "turbinia.initContainer" . | nindent 8 }} 
      containers:
        - name: server
          securityContext:
              {{- toYaml .Values.turbinia.server.securityContext | nindent 12 }}
          image: "{{ .Values.turbinia.server.image.repository }}:{{ .Values.turbinia.server.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.turbinia.server.image.pullPolicy }}
          env:
            - name: TURBINIA_EXTRA_ARGS
              value: "-d"
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - mountPath: /mnt/turbiniavolume
              name: turbiniavolume
            - mountPath: /etc/turbinia
              name: turbinia-configs
          ports:
            {{- if .Values.metrics.enabled }}
            - containerPort: {{ .Values.metrics.port }}
            {{- end }}
          resources:
            {{- toYaml .Values.turbinia.server.resources | nindent 12 }}
      volumes:
        - name: turbiniavolume
          persistentVolumeClaim:
            claimName: {{ include "osdfir.pvc.name"  . }}
            readOnly: false
        - name: init-turbinia
          configMap:
            name: {{ .Release.Name }}-turbinia-initconfig
            defaultMode: 0744
        - name: turbinia-configs
          emptyDir: {}
        {{- if $userconfigs }}
        - name: user-configs
          configMap:
            name: {{ .Release.Name }}-turbinia-config
        {{- end }}
      {{- with .Values.turbinia.server.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.turbinia.server.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.turbinia.server.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}